spring:
  application:
    name: cloud-dept
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
      #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-dept8002
    prefer-ip-address: true
info:
  app.name: cloudgeneral
  company.name: www.jufo.com
  build.artifact: $project.artifactId$
  build.version: $project.version$
  